#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum class STATE { RIGHT, UP, LOOK, POSITION };
	enum class PROTOTYPE { GAMEOBJECT, COMPONENT };
	enum class RENDERGROUP { RG_PRIORITY, RG_TILE, RG_NONBLEND, RG_BLEND, RG_UI, RG_END };
	enum class WINMODE { MODE_FULL, MODE_WIN, MODE_END };

	enum class MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum class MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum class TEXTURE { RECT, CUBE };
	enum class COLLIDER_SHAPE { RECT, CUBE };
	enum class COLLIDER_DIR {LEFT, RIGHT, FRONT, BACK, TOP, BOTTOM, CD_END};

	enum class DIMENSION { NONE , TOODEE, CHANGE ,TOPDEE };
	
	enum class CHANNELID { SOUND_MENU, SOUND_BOSS, SOUND_PLAYER , SOUND_RESOURCE, SOUND_EFFECT, SOUND_EFFECT2, SOUND_EFFECT3, SOUND_EFFECT4, SOUND_LOOP ,SOUND_BGM, SOUND_END };

	enum class EVENT_KEY {
		ENTER_PORTAL,
		EXIT_PORTAL,
		CAN_CLEAR,
		BLOCK_BREAK,
		ADD_KEY,
		GET_KEY,
		SIG_MONSTER,
		CHANGE_CAM,
		FIN_ACTION,
		SINK_BLOCK,
		SINK_OPEN,
		REDBUTTON_PRESSED,
		REDBUTTON_UNPRESSED,
		CHANGE_LEVEL,
		MAINMENU_BUTTON,
		MAINMENU_STAGE,
		MAINMENU_STAGE_SELECT,
		CAM_SHAKING,
		LOADINGSCREEN,
		FINALBOSS_ATTACK,
		PLAYERS_POSITION,
		SPEECH,
		STAGEBOSS_DAMAGED,
		STAGEBOSS_RESET,
		REMOVE_SPIKE
	};
	

}
#endif // Engine_Enum_h__


